name: KhiCAS Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  KhiCAS:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Install dependencies
        run: apt list --all-versions libtool && sudo apt install gcc-arm-none-eabi libtool=2.4.6-15
      - name: Get KhiCAS
        run: wget -qO- https://www-fourier.univ-grenoble-alpes.fr/~parisse/numworks/khiext.tgz | tar -xz
      - name: Build KhiCAS
        run: cd khiext && make
