name: KhiCAS Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  KhiCAS:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          #sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev
          #sudo apt-get install build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi
          sudo apt-get install libmpfr-dev
      - name: Get KhiCAS
        run: wget -qO- https://www-fourier.univ-grenoble-alpes.fr/~parisse/numworks/khiext.tgz | tar -xz
      - name: Fix libtool
        run: |
          cd ./khiext/apps/KhiCAS/src/mpfi-1.5.4/
          aclocal
          autoconf
          automake --add-missing
          ./configure
      - name: Build KhiCAS
        run: cd ./khiext/apps/KhiCAS/ && make -j2 && ls -l
